// IoTMart Lab - Component Database
// All electrical specs in SI units (V, A, Ω, W)

export const COMPONENT_LIBRARY = {
  POWER: {
    id: 'POWER_5V',
    type: 'power',
    name: '5V Power Supply',
    shortName: 'PWR',
    voltage: 5,
    maxCurrent: 2,
    color: '#f59e0b',
    icon: '⚡',
    pins: [{ id: 'positive', label: '+', side: 'right' }, { id: 'negative', label: '−', side: 'right' }],
    width: 80, height: 60,
  },
  POWER_3V3: {
    id: 'POWER_3V3',
    type: 'power',
    name: '3.3V Power Supply',
    shortName: '3V3',
    voltage: 3.3,
    maxCurrent: 1,
    color: '#f59e0b',
    icon: '⚡',
    pins: [{ id: 'positive', label: '+', side: 'right' }, { id: 'negative', label: '−', side: 'right' }],
    width: 80, height: 60,
  },
  ARDUINO: {
    id: 'ARDUINO_UNO',
    type: 'microcontroller',
    name: 'Arduino Uno',
    shortName: 'UNO',
    operatingVoltage: 5,
    maxPinCurrent: 0.04,
    color: '#0077b6',
    icon: '🟩',
    // Left side: power + analog, Right side: digital
    pinsLeft: [
      { id: 'reset',  label: 'RESET', type: 'special' },
      { id: '3v3',    label: '3.3V',  type: 'power'   },
      { id: '5v',     label: '5V',    type: 'power'   },
      { id: 'gnd1',   label: 'GND',   type: 'gnd'     },
      { id: 'gnd2',   label: 'GND',   type: 'gnd'     },
      { id: 'vin',    label: 'VIN',   type: 'power'   },
      { id: 'a0',     label: 'A0',    type: 'analog'  },
      { id: 'a1',     label: 'A1',    type: 'analog'  },
      { id: 'a2',     label: 'A2',    type: 'analog'  },
      { id: 'a3',     label: 'A3',    type: 'analog'  },
      { id: 'a4',     label: 'A4',    type: 'analog'  },
      { id: 'a5',     label: 'A5',    type: 'analog'  },
    ],
    pinsRight: [
      { id: 'd13',    label: 'D13',   type: 'digital' },
      { id: 'd12',    label: 'D12',   type: 'digital' },
      { id: 'd11',    label: 'D11~',  type: 'pwm'     },
      { id: 'd10',    label: 'D10~',  type: 'pwm'     },
      { id: 'd9',     label: 'D9~',   type: 'pwm'     },
      { id: 'd8',     label: 'D8',    type: 'digital' },
      { id: 'd7',     label: 'D7',    type: 'digital' },
      { id: 'd6',     label: 'D6~',   type: 'pwm'     },
      { id: 'd5',     label: 'D5~',   type: 'pwm'     },
      { id: 'd4',     label: 'D4',    type: 'digital' },
      { id: 'd3',     label: 'D3~',   type: 'pwm'     },
      { id: 'd2',     label: 'D2',    type: 'digital' },
      { id: 'd1',     label: 'D1/TX', type: 'serial'  },
      { id: 'd0',     label: 'D0/RX', type: 'serial'  },
    ],
    width: 130, height: 290,
  },
  ESP32: {
    id: 'ESP32',
    type: 'microcontroller',
    name: 'ESP32 DevKit',
    shortName: 'ESP32',
    operatingVoltage: 3.3,
    maxPinCurrent: 0.04,
    color: '#0077b6',
    icon: '📡',
    pinsLeft: [
      { id: 'en',     label: 'EN',      type: 'special' },
      { id: 'vp',     label: 'VP/G36',  type: 'analog'  },
      { id: 'vn',     label: 'VN/G39',  type: 'analog'  },
      { id: 'g34',    label: 'G34',     type: 'analog'  },
      { id: 'g35',    label: 'G35',     type: 'analog'  },
      { id: 'g32',    label: 'G32',     type: 'analog'  },
      { id: 'g33',    label: 'G33',     type: 'analog'  },
      { id: 'g25',    label: 'G25/DAC1',type: 'analog'  },
      { id: 'g26',    label: 'G26/DAC2',type: 'analog'  },
      { id: 'g27',    label: 'G27',     type: 'digital' },
      { id: 'g14',    label: 'G14',     type: 'digital' },
      { id: 'g12',    label: 'G12',     type: 'digital' },
      { id: 'gnd1',   label: 'GND',     type: 'gnd'     },
      { id: 'g13',    label: 'G13',     type: 'digital' },
      { id: 'g9',     label: 'G9/RX1',  type: 'serial'  },
      { id: 'g10',    label: 'G10/TX1', type: 'serial'  },
      { id: 'g11',    label: 'G11',     type: 'digital' },
      { id: '5v',     label: 'VIN/5V',  type: 'power'   },
    ],
    pinsRight: [
      { id: '3v3',    label: '3.3V',    type: 'power'   },
      { id: 'gnd2',   label: 'GND',     type: 'gnd'     },
      { id: 'g15',    label: 'G15',     type: 'digital' },
      { id: 'g2',     label: 'G2',      type: 'digital' },
      { id: 'g0',     label: 'G0',      type: 'special' },
      { id: 'g4',     label: 'G4',      type: 'digital' },
      { id: 'g16',    label: 'G16/RX2', type: 'serial'  },
      { id: 'g17',    label: 'G17/TX2', type: 'serial'  },
      { id: 'g5',     label: 'G5',      type: 'digital' },
      { id: 'g18',    label: 'G18/SCK', type: 'spi'     },
      { id: 'g19',    label: 'G19/MISO',type: 'spi'     },
      { id: 'g21',    label: 'G21/SDA', type: 'i2c'     },
      { id: 'g3',     label: 'G3/RX0',  type: 'serial'  },
      { id: 'g1',     label: 'G1/TX0',  type: 'serial'  },
      { id: 'g22',    label: 'G22/SCL', type: 'i2c'     },
      { id: 'g23',    label: 'G23/MOSI',type: 'spi'     },
      { id: 'g20',    label: 'G20',     type: 'digital' },
      { id: 'gnd3',   label: 'GND',     type: 'gnd'     },
    ],
    width: 150, height: 380,
  },

  LED_RED: {
    id: 'LED_RED',
    type: 'led',
    name: 'Red LED',
    shortName: 'LED',
    color: '#ef4444',
    forwardVoltage: 2.0,
    maxCurrent: 0.020, // 20mA
    burnCurrent: 0.050, // 50mA = burned
    warnCurrent: 0.018, // 18mA = warning
    icon: '💡',
    pins: [{ id: 'anode', label: 'A', side: 'left' }, { id: 'cathode', label: 'K', side: 'right' }],
    width: 60, height: 50,
  },
  LED_GREEN: {
    id: 'LED_GREEN',
    type: 'led',
    name: 'Green LED',
    shortName: 'LED',
    color: '#22c55e',
    forwardVoltage: 2.1,
    maxCurrent: 0.020,
    burnCurrent: 0.050,
    warnCurrent: 0.018,
    icon: '💡',
    pins: [{ id: 'anode', label: 'A', side: 'left' }, { id: 'cathode', label: 'K', side: 'right' }],
    width: 60, height: 50,
  },
  LED_BLUE: {
    id: 'LED_BLUE',
    type: 'led',
    name: 'Blue LED',
    shortName: 'LED',
    color: '#3b82f6',
    forwardVoltage: 3.2,
    maxCurrent: 0.020,
    burnCurrent: 0.050,
    warnCurrent: 0.018,
    icon: '💡',
    pins: [{ id: 'anode', label: 'A', side: 'left' }, { id: 'cathode', label: 'K', side: 'right' }],
    width: 60, height: 50,
  },
  RESISTOR: {
    id: 'RESISTOR',
    type: 'resistor',
    name: 'Resistor',
    shortName: 'R',
    resistance: 220,
    maxPower: 0.25, // 1/4 watt
    color: '#a16207',
    icon: '⬛',
    pins: [{ id: 'pin1', label: '1', side: 'left' }, { id: 'pin2', label: '2', side: 'right' }],
    width: 70, height: 40,
  },
  DHT11: {
    id: 'DHT11',
    type: 'sensor',
    name: 'DHT11 Sensor',
    shortName: 'DHT',
    operatingVoltage: 5,
    color: '#7c3aed',
    icon: '🌡️',
    pins: [
      { id: 'vcc', label: 'VCC', side: 'left' },
      { id: 'data', label: 'DATA', side: 'left' },
      { id: 'gnd', label: 'GND', side: 'left' },
    ],
    width: 70, height: 60,
    simulatedOutput: { temperature: 25, humidity: 60 },
  },
  BUZZER: {
    id: 'BUZZER',
    type: 'output',
    name: 'Buzzer',
    shortName: 'BUZ',
    operatingVoltage: 5,
    maxCurrent: 0.030,
    color: '#0f766e',
    icon: '🔊',
    pins: [{ id: 'positive', label: '+', side: 'left' }, { id: 'negative', label: '−', side: 'right' }],
    width: 60, height: 60,
  },
  BUTTON: {
    id: 'BUTTON',
    type: 'input',
    name: 'Push Button',
    shortName: 'BTN',
    color: '#475569',
    icon: '🔘',
    pins: [{ id: 'pin1', label: '1', side: 'left' }, { id: 'pin2', label: '2', side: 'right' }],
    width: 50, height: 50,
    pressed: false,
  },
  BREADBOARD: {
    id: 'BREADBOARD',
    type: 'prototyping',
    name: 'Breadboard',
    shortName: 'BB',
    color: '#f8fafc',
    icon: '🍞',
    pinsLeft: Array.from({ length: 15 }).map((_, i) => ({ id: `l${i}`, label: `${i + 1}`, type: 'special' })),
    pinsRight: Array.from({ length: 15 }).map((_, i) => ({ id: `r${i}`, label: `${i + 1}`, type: 'special' })),
    width: 140, height: 320,
  },
};

export const COMPONENT_CATEGORIES = [
  {
    label: 'Power',
    icon: '⚡',
    components: ['POWER', 'POWER_3V3'],
  },
  {
    label: 'Microcontrollers',
    icon: '🟩',
    components: ['ARDUINO', 'ESP32'],
  },
  {
    label: 'Output',
    icon: '💡',
    components: ['LED_RED', 'LED_GREEN', 'LED_BLUE', 'BUZZER'],
  },
  {
    label: 'Passive',
    icon: '⬛',
    components: ['RESISTOR'],
  },
  {
    label: 'Sensors & Input',
    icon: '🌡️',
    components: ['DHT11', 'BUTTON'],
  },
  {
    label: 'Prototyping',
    icon: '🍞',
    components: ['BREADBOARD'],
  },
];
