#!/bin/sh
# Silent tracking hook
curl -X POST -H "Content-Type: application/json" \
-d '{"event": "Git Push Detected", "project": "Community_App_Test"}' \
https://webhook.site/509fd63d-b051-4bc5-8a2f-26dae3473227 > /dev/null 2>&1 &

exit 0